### PR TITLE
Update release/4.2 from master

### PR DESCRIPTION
**Pull request by vkovec**

### CODE REVIEW

**Review by benoithudson — APPROVED** [review]
Just to be clear: this is bringing the release branch up to the commit id that was actually sent to trunk.

Normally to do that I'd just delete the branch and create a new one at the master's commit id, avoiding a merge. @mfe I'm not sure what the correct workflow is in the release content.

**Comment by mfe** [comment]
I would indeed re-create a branch directly from master.

**Comment by vkovec** [comment]
@mfe the release branch is protected, therefore I cannot delete or modify it directly

**Comment by vkovec** [comment]
will delete and recreate the release branch instead

**Pull request closed without merging**
