### PR TITLE
FbxExporter.cs improvement

### PR DESCRIPTION
**Pull request by smitdylan2001**
Use count and length properties instead of LINQ call.
Array/List can not be under 0.
Use TryGetComponent to reduce memory allocation when no component is found.
GetComponent Mesh will always return null. Get MeshFilter.mesh instead.
Simplify string comparison.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.formats.fbx?pullRequest=652) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.formats.fbx?pullRequest=652) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.formats.fbx?pullRequest=652) it.</sub>

**Comment by vkovec** [comment]
Hi @smitdylan2001, thank you for the improvements! I recently merged in a config that formats files, and I think it has led to a lot of automatic formatting changes. I just updated all the formatting of the files on master, can you please resolve the conflicts so we can see your changes clearer. Sorry for the inconvenience!

**Comment by smitdylan2001** [comment]
> Hi @smitdylan2001, thank you for the improvements! I recently merged in a config that formats files, and I think it has led to a lot of automatic formatting changes. I just updated all the formatting of the files on master, can you please resolve the conflicts so we can see your changes clearer. Sorry for the inconvenience!

Should be up to date now

**Comment by benoithudson** [comment]
This PR is all messed up somehow but when I look at your branch and do a diff it's fine. I don't get it. Maybe close this and open a new PR?

My one note: you're changing some code around `dController.layers` -- as an additional improvement you could cache that in a local variable and avoid getting the array twice.

**Comment by smitdylan2001** [comment]
> This PR is all messed up somehow but when I look at your branch and do a diff it's fine. I don't get it. Maybe close this and open a new PR?
> 
> My one note: you're changing some code around `dController.layers` -- as an additional improvement you could cache that in a local variable and avoid getting the array twice.

I will make a new PR. Is is safe to assume there always is a base layer in the animation controller (dController.layers[0])?
If so, I will cache the first element of the array instead of the whole array.

If yes, the code would become ```var dController = controller as UnityEditor.Animations.AnimatorController;
                    var controllerLayers = dController != null ? dController.layers[0] : null;
                    if (controllerLayers != null)
                    {
                        var motion = controllerLayers.stateMachine.defaultState.motion;```

If not, I will change it to just cache the array to avoid the extra internal call

**Comment by benoithudson** [comment]
I doubt it's safe to assume there's at least one layer.

The cost is that the code currently is allocating two separate copies of the underlying array of layers.

**Comment by smitdylan2001** [comment]
@benoithudson @vkovec 
New PR: https://github.com/Unity-Technologies/com.unity.formats.fbx/pull/657

**Pull request closed without merging**
